# Webサーバの設定
web-server:
  # イメージの指定
  image: wordpress

  # ポート転送設定
  ports:
    - "80:80"

  # コンテナのリンク指定
  links:
    - "db-server:mysql"

# DBサーバの設定
db-server:
  # イメージの指定
  image: mysql

  # データ保存先の指定
  volumes_from:
    - data-only

  # 環境変数の指定
  environment:
    MYSQL_ROOT_PASSWORD: password
